services:
  frontend:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ./docker/entrypoints/frontend.sh
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
