# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.6'

gem 'bootsnap', require: false
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'rails', '~> 7.1.3'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'devise', '~> 4.9'
gem 'omniauth', '~> 2.1'
gem 'omniauth-google-oauth2', '~> 1.1'

gem 'grape', '~> 2.1'
gem 'grape-entity', '~> 1.0.0'
gem 'grape-swagger', '~> 2.0'

gem 'devise-jwt', '~> 0.11.0'
gem 'jsonapi-serializer', '~> 2.2'

gem 'rack-cors', '~> 2.0'
gem 'simple_command', '~> 1.0'

gem 'grape_on_rails_routes'

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
end

gem 'rswag-ui', '~> 2.13'

gem 'dotenv-rails', '~> 3.1'
